function output_StimData = copy_Stim_CurrentClampSeries(input_acquisitionData)

%%% imput_acquisitionData: single index_xx from the nwb file 
%%% output_acquisitionData: uncompressed nwb data, that contains the parameters 

StimData = input_acquisitionData;


extracted.electrode = StimData.electrode;
extracted.gain = StimData.gain;
extracted.stimulus_description = StimData.stimulus_description;
extracted.sweep_number = StimData.sweep_number;
extracted.starting_time_unit = StimData.starting_time_unit;
extracted.timestamps_interval = StimData.timestamps_interval;
extracted.timestamps_unit = StimData.timestamps_unit;
extracted.comments = StimData.comments;
extracted.control = StimData.control;
extracted.control_description = StimData.control_description;
% extracted.data = acquisitionData.data; %%
extracted.data_conversion = StimData.data_conversion;
extracted.data_resolution = StimData.data_resolution;
extracted.data_unit = StimData.data_unit;
extracted.description = StimData.description;
extracted.starting_time = StimData.starting_time;
extracted.starting_time_rate = StimData.starting_time_rate;
extracted.timestamps = StimData.timestamps;


%% compress and write
RawStimData = StimData.data.load;

fData_compressed=types.untyped.DataPipe('data', RawStimData.');

output_StimData = types.core.CurrentClampStimulusSeries(...
                                                'electrode', extracted.electrode, ...
                                                'gain', extracted.gain, ...
                                                'stimulus_description', extracted.stimulus_description, ...
                                                'sweep_number', extracted.sweep_number, ...
                                                'starting_time_unit', extracted.starting_time_unit, ...
                                                'timestamps_interval', extracted.timestamps_interval, ...
                                                'timestamps_unit', extracted.timestamps_unit, ...
                                                'comments', extracted.comments, ...
                                                'control', extracted.control, ...
                                                'control_description', extracted.control_description, ...
                                                'data_conversion', extracted.data_conversion, ...
                                                'data_resolution', extracted.data_resolution, ...
                                                'data_unit', extracted.data_unit, ...
                                                'description', extracted.description, ...
                                                'starting_time', extracted.starting_time, ...
                                                'starting_time_rate', extracted.starting_time_rate, ...
                                                'timestamps', extracted.timestamps,...
                                                'data', fData_compressed);


end