function output_acquisitionData = copy_CurrentClampSeries(input_acquisitionData)

acquisitionData = input_acquisitionData;

extraceted.bias_current = acquisitionData.bias_current;
extraceted.bridge_balance = acquisitionData.bridge_balance;
extraceted.capacitance_compensation = acquisitionData.capacitance_compensation;
extracted.electrode = acquisitionData.electrode;
extracted.gain = acquisitionData.gain;
extracted.stimulus_description = acquisitionData.stimulus_description;
extracted.sweep_number = acquisitionData.sweep_number;
extracted.starting_time_unit = acquisitionData.starting_time_unit;
extracted.timestamps_interval = acquisitionData.timestamps_interval;
extracted.timestamps_unit = acquisitionData.timestamps_unit;
extracted.comments = acquisitionData.comments;
extracted.control = acquisitionData.control;
extracted.control_description = acquisitionData.control_description;
% extracted.data = acquisitionData.data; %%
extracted.data_conversion = acquisitionData.data_conversion;
extracted.data_resolution = acquisitionData.data_resolution;
extracted.data_unit = acquisitionData.data_unit;
extracted.description = acquisitionData.description;
extracted.starting_time = acquisitionData.starting_time;
extracted.starting_time_rate = acquisitionData.starting_time_rate;
extracted.timestamps = acquisitionData.timestamps;


%% compress and write 2nd attempt, EZ currentseries response kiszedése
RawStimData = acquisitionData.data.load;

fData_compressed=types.untyped.DataPipe('data', RawStimData.');

output_acquisitionData = types.core.CurrentClampSeries(...
                                                'bias_current', extraceted.bias_current, ...
                                                'bridge_balance', extraceted.bridge_balance, ...
                                                'capacitance_compensation', extraceted.capacitance_compensation, ...
                                                'electrode', extracted.electrode, ...
                                                'gain', extracted.gain, ...
                                                'stimulus_description', extracted.stimulus_description, ...
                                                'sweep_number', extracted.sweep_number, ...
                                                'starting_time_unit', extracted.starting_time_unit, ...
                                                'timestamps_interval', extracted.timestamps_interval, ...
                                                'timestamps_unit', extracted.timestamps_unit, ...
                                                'comments', extracted.comments, ...
                                                'control', extracted.control, ...
                                                'control_description', extracted.control_description, ...
                                                'data_conversion', extracted.data_conversion, ...
                                                'data_resolution', extracted.data_resolution, ...
                                                'data_unit', extracted.data_unit, ...
                                                'description', extracted.description, ...
                                                'starting_time', extracted.starting_time, ...
                                                'starting_time_rate', extracted.starting_time_rate, ...
                                                'timestamps', extracted.timestamps,...
                                                'data', fData_compressed);
                                            
end 